# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\akashbad\Documents\6.115\Final Project\LauncherController.cydsn\CapSense_CSD_Design01.cydsn\CapSense_CSD_Design01.cyprj
# Date: Mon, 12 May 2014 18:41:08 GMT
#set_units -time ns
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CapSense_CSD_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 3 5} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]


# Component constraints for C:\Users\akashbad\Documents\6.115\Final Project\LauncherController.cydsn\CapSense_CSD_Design01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\akashbad\Documents\6.115\Final Project\LauncherController.cydsn\CapSense_CSD_Design01.cydsn\CapSense_CSD_Design01.cyprj
# Date: Mon, 12 May 2014 18:40:54 GMT
