/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <LCD.h>
#include <Target_UART.h>
#include <RX_INT.h>
#include <Launcher_UART.h>
#include <Launcher_UART_audio.h>
#include <Launcher_UART_cdc.h>
#include <Launcher_UART_hid.h>
#include <Launcher_UART_midi.h>
#include <Launcher_UART_pvt.h>
#include <CapSense.h>
#include <CapSense_CSHL.h>
#include <CapSense_Pins.h>
#include <CapSense_TunerHelper.h>
#include <Target_Control_aliases.h>
#include <Target_Control.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <Target_UART_IntClock.h>
#include <Launcher_UART_Dm_aliases.h>
#include <Launcher_UART_Dm.h>
#include <Launcher_UART_Dp_aliases.h>
#include <Launcher_UART_Dp.h>
#include <CapSense_CompCH0.h>
#include <CapSense_IdacCH0.h>
#include <CapSense_AMuxCH0.h>
#include <CapSense_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

